import os

GENERATION_DIR = os.environ.get('GENERATION_DIR')
CONFIGURATION_REFERENCE_DEFAULT = os.environ.get('CONFIGURATION_REFERENCE_DEFAULT')
REQUEST_REFERENCE_DEFAULT = os.environ.get('REQUEST_REFERENCE_DEFAULT')
DEPLOYMENT_MODE_DEFAULT = os.environ.get('DEPLOYMENT_MODE_DEFAULT')
GENERATION_PROVIDER_DEFAULT = os.environ.get('GENERATION_PROVIDER_DEFAULT')
GENERATION_FRAMEWORK_DEFAULT = os.environ.get('GENERATION_FRAMEWORK_DEFAULT')
