name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run the compose network
      run: make run
    - name: Run the tests
      run: docker-compose exec -T hamlet-cli /bin/bash -c 'source ~/.bashrc && make tests'
