name: testing

on:
  push:

jobs:
  run-testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: install os extras
      run: |
        sudo apt-get install \
            jq dos2unix

    - name: install reqs
      run: |
        pip install -r requirements/dev.txt
        pip install ./

    - name: Run tests
      run: |
        make tests
